Time to read keyword file = 0.562 seconds
Warning - NODE 2900 not found:
  Referenced in *CONSTRAINED_LINEAR_GLOBAL ID = 779
Warning - NODE 2900 not found:
  Referenced in *CONSTRAINED_LINEAR_GLOBAL ID = 780
Message 0
Time to read keyword file = 0.219 seconds
Message 0
Time to read keyword file = 0.250 seconds
Message 0
Time to read keyword file = 0.250 seconds
Message 0
Time to read keyword file = 0.312 seconds
Message 0
