*CONSTRAINED_LINEAR_GLOBAL
         1
       185         2       1.0
      8231         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         2
       185         3       1.0
      8231         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         3
       186         2       1.0
      8230         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         4
       186         3       1.0
      8230         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         5
       187         2       1.0
      8229         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         6
       187         3       1.0
      8229         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         7
       188         2       1.0
      8228         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         8
       188         3       1.0
      8228         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         9
       217         2       1.0
      8199         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        10
       217         3       1.0
      8199         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        11
       218         2       1.0
      8198         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        12
       218         3       1.0
      8198         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        13
       247         2       1.0
      8169         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        14
       247         3       1.0
      8169         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        15
       248         2       1.0
      8168         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        16
       248         3       1.0
      8168         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        17
       263         2       1.0
      8153         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        18
       263         3       1.0
      8153         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        19
       425         2       1.0
      7991         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        20
       425         3       1.0
      7991         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        21
       426         2       1.0
      7990         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        22
       426         3       1.0
      7990         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        23
       427         2       1.0
      7989         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        24
       427         3       1.0
      7989         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        25
       428         2       1.0
      7988         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        26
       428         3       1.0
      7988         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        27
       457         2       1.0
      7959         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        28
       457         3       1.0
      7959         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        29
       458         2       1.0
      7958         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        30
       458         3       1.0
      7958         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        31
       547         2       1.0
      7869         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        32
       547         3       1.0
      7869         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        33
       548         2       1.0
      7868         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        34
       548         3       1.0
      7868         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        35
       577         2       1.0
      7839         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        36
       577         3       1.0
      7839         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        37
       578         2       1.0
      7838         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        38
       578         3       1.0
      7838         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        39
       607         2       1.0
      7809         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        40
       607         3       1.0
      7809         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        41
       608         2       1.0
      7808         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        42
       608         3       1.0
      7808         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        43
       665         2       1.0
      7660         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        44
       665         3       1.0
      7660         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        45
       666         2       1.0
      7659         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        46
       666         3       1.0
      7659         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        47
       667         2       1.0
      7658         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        48
       667         3       1.0
      7658         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        49
       668         2       1.0
      7657         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        50
       668         3       1.0
      7657         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        51
      2524         2       1.0
      9368         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        52
      2524         3       1.0
      9368         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        53
      2527         2       1.0
      9371         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        54
      2527         3       1.0
      9371         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        55
      2675         2       1.0
      9519         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        56
      2675         3       1.0
      9519         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        57
      2705         2       1.0
      9549         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        58
      2705         3       1.0
      9549         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        59
      2735         2       1.0
      9579         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        60
      2735         3       1.0
      9579         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        61
      2825         2       1.0
      9669         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        62
      2825         3       1.0
      9669         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        63
      2826         2       1.0
      9670         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        64
      2826         3       1.0
      9670         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        65
      2855         2       1.0
      9699         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        66
      2855         3       1.0
      9699         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        67
      2856         2       1.0
      9700         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        68
      2856         3       1.0
      9700         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        69
      2857         2       1.0
      9701         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        70
      2857         3       1.0
      9701         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        71
      2858         2       1.0
      9702         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        72
      2858         3       1.0
      9702         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        73
      3020         2       1.0
      9864         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        74
      3020         3       1.0
      9864         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        75
      3035         2       1.0
      9879         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        76
      3035         3       1.0
      9879         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        77
      3036         2       1.0
      9880         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        78
      3036         3       1.0
      9880         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        79
      3065         2       1.0
      9909         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        80
      3065         3       1.0
      9909         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        81
      3066         2       1.0
      9910         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        82
      3066         3       1.0
      9910         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        83
      3095         2       1.0
      9939         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        84
      3095         3       1.0
      9939         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        85
      3096         2       1.0
      9940         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        86
      3096         3       1.0
      9940         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        87
      3097         2       1.0
      9941         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        88
      3097         3       1.0
      9941         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        89
      3098         2       1.0
      9942         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        90
      3098         3       1.0
      9942         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        91
      4237         2       1.0
     11081         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        92
      4237         3       1.0
     11081         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        93
      4238         2       1.0
     11082         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        94
      4238         3       1.0
     11082         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        95
      4386         2       1.0
     11230         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        96
      4386         3       1.0
     11230         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        97
      4387         2       1.0
     11231         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        98
      4387         3       1.0
     11231         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        99
      4416         2       1.0
     11260         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       100
      4416         3       1.0
     11260         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       101
      4417         2       1.0
     11261         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       102
      4417         3       1.0
     11261         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       103
      4446         2       1.0
     11290         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       104
      4446         3       1.0
     11290         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       105
      4447         2       1.0
     11291         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       106
      4447         3       1.0
     11291         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       107
      4537         2       1.0
     11381         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       108
      4537         3       1.0
     11381         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       109
      4568         2       1.0
     11412         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       110
      4568         3       1.0
     11412         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       111
      4569         2       1.0
     11413         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       112
      4569         3       1.0
     11413         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       113
      4731         2       1.0
     11575         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       114
      4731         3       1.0
     11575         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       115
      4746         2       1.0
     11590         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       116
      4746         3       1.0
     11590         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       117
      4747         2       1.0
     11591         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       118
      4747         3       1.0
     11591         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       119
      4776         2       1.0
     11620         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       120
      4776         3       1.0
     11620         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       121
      4777         2       1.0
     11621         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       122
      4777         3       1.0
     11621         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       123
      4806         2       1.0
     11650         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       124
      4806         3       1.0
     11650         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       125
      4807         2       1.0
     11651         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       126
      4807         3       1.0
     11651         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       127
      4808         2       1.0
     11652         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       128
      4808         3       1.0
     11652         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       129
      4809         2       1.0
     11653         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       130
      4809         3       1.0
     11653         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       131
      5949         2       1.0
     12793         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       132
      5949         3       1.0
     12793         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       133
      6097         2       1.0
     12941         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       134
      6097         3       1.0
     12941         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       135
      6127         2       1.0
     12971         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       136
      6127         3       1.0
     12971         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       137
      6157         2       1.0
     13001         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       138
      6157         3       1.0
     13001         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       139
      6248         2       1.0
     13092         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       140
      6248         3       1.0
     13092         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       141
      6279         2       1.0
     13123         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       142
      6279         3       1.0
     13123         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       143
      6280         2       1.0
     13124         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       144
      6280         3       1.0
     13124         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       145
      6442         2       1.0
     13286         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       146
      6442         3       1.0
     13286         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       147
      6457         2       1.0
     13301         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       148
      6457         3       1.0
     13301         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       149
      6458         2       1.0
     13302         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       150
      6458         3       1.0
     13302         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       151
      6487         2       1.0
     13331         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       152
      6487         3       1.0
     13331         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       153
      6488         2       1.0
     13332         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       154
      6488         3       1.0
     13332         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       155
      6517         2       1.0
     13361         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       156
      6517         3       1.0
     13361         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       157
      6518         2       1.0
     13362         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       158
      6518         3       1.0
     13362         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       159
      6519         2       1.0
     13363         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       160
      6519         3       1.0
     13363         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       161
      6520         2       1.0
     13364         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       162
      6520         3       1.0
     13364         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         1
      1984         1       1.0
      1208         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         2
      1984         2       1.0
      1208         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         3
      1984         3       1.0
      1208         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         4
      1985         1       1.0
      1207         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         5
      1985         2       1.0
      1207         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         6
      1985         3       1.0
      1207         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         7
      2045         1       1.0
      1147         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         8
      2045         2       1.0
      1147         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         9
      2045         3       1.0
      1147         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        10
      2104         1       1.0
      1088         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        11
      2104         2       1.0
      1088         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        12
      2104         3       1.0
      1088         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        13
      2105         1       1.0
      1087         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        14
      2105         2       1.0
      1087         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        15
      2105         3       1.0
      1087         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        16
      2164         1       1.0
      1028         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        17
      2164         2       1.0
      1028         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        18
      2164         3       1.0
      1028         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        19
      2165         1       1.0
      1027         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        20
      2165         2       1.0
      1027         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        21
      2165         3       1.0
      1027         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        22
      2194         1       1.0
       998         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        23
      2194         2       1.0
       998         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        24
      2194         3       1.0
       998         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        25
      2195         1       1.0
       997         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        26
      2195         2       1.0
       997         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        27
      2195         3       1.0
       997         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        28
      2224         1       1.0
       968         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        29
      2224         2       1.0
       968         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        30
      2224         3       1.0
       968         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        31
      2225         1       1.0
       967         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        32
      2225         2       1.0
       967         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        33
      2225         3       1.0
       967         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        34
      2226         1       1.0
       966         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        35
      2226         2       1.0
       966         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        36
      2226         3       1.0
       966         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        37
      2227         1       1.0
       965         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        38
      2227         2       1.0
       965         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        39
      2227         3       1.0
       965         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        40
      2284         1       1.0
       908         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        41
      2284         2       1.0
       908         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        42
      2284         3       1.0
       908         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        43
      2299         1       1.0
       893         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        44
      2299         2       1.0
       893         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        45
      2299         3       1.0
       893         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        46
      2314         1       1.0
       878         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        47
      2314         2       1.0
       878         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        48
      2314         3       1.0
       878         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        49
      2315         1       1.0
       877         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        50
      2315         2       1.0
       877         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        51
      2315         3       1.0
       877         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        52
      2359         1       1.0
       833         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        53
      2359         2       1.0
       833         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        54
      2359         3       1.0
       833         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        55
      2360         1       1.0
       832         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        56
      2360         2       1.0
       832         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        57
      2360         3       1.0
       832         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        58
      2434         1       1.0
       758         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        59
      2434         2       1.0
       758         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        60
      2434         3       1.0
       758         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        61
      2435         1       1.0
       757         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        62
      2435         2       1.0
       757         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        63
      2435         3       1.0
       757         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        64
      2464         1       1.0
       728         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        65
      2464         2       1.0
       728         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        66
      2464         3       1.0
       728         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        67
      2465         1       1.0
       727         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        68
      2465         2       1.0
       727         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        69
      2465         3       1.0
       727         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        70
      2466         1       1.0
       726         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        71
      2466         2       1.0
       726         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        72
      2466         3       1.0
       726         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        73
      2467         1       1.0
       725         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        74
      2467         2       1.0
       725         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        75
      2467         3       1.0
       725         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        76
      5406         1       1.0
      3695         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        77
      5406         2       1.0
      3695         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        78
      5406         3       1.0
      3695         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        79
      5467         1       1.0
      3756         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        80
      5467         2       1.0
      3756         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        81
      5467         3       1.0
      3756         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        82
      5526         1       1.0
      3815         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        83
      5526         2       1.0
      3815         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        84
      5526         3       1.0
      3815         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        85
      5527         1       1.0
      3816         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        86
      5527         2       1.0
      3816         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        87
      5527         3       1.0
      3816         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        88
      5586         1       1.0
      3875         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        89
      5586         2       1.0
      3875         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        90
      5586         3       1.0
      3875         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        91
      5616         1       1.0
      3905         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        92
      5616         2       1.0
      3905         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        93
      5616         3       1.0
      3905         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        94
      5646         1       1.0
      3935         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        95
      5646         2       1.0
      3935         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        96
      5646         3       1.0
      3935         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        97
      5649         1       1.0
      3938         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        98
      5649         2       1.0
      3938         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        99
      5649         3       1.0
      3938         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       100
      5706         1       1.0
      3995         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       101
      5706         2       1.0
      3995         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       102
      5706         3       1.0
      3995         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       103
      5721         1       1.0
      4010         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       104
      5721         2       1.0
      4010         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       105
      5721         3       1.0
      4010         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       106
      5736         1       1.0
      4025         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       107
      5736         2       1.0
      4025         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       108
      5736         3       1.0
      4025         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       109
      5737         1       1.0
      4026         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       110
      5737         2       1.0
      4026         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       111
      5737         3       1.0
      4026         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       112
      5781         1       1.0
      4070         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       113
      5781         2       1.0
      4070         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       114
      5781         3       1.0
      4070         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       115
      5782         1       1.0
      4071         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       116
      5782         2       1.0
      4071         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       117
      5782         3       1.0
      4071         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       118
      5856         1       1.0
      4145         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       119
      5856         2       1.0
      4145         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       120
      5856         3       1.0
      4145         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       121
      5857         1       1.0
      4146         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       122
      5857         2       1.0
      4146         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       123
      5857         3       1.0
      4146         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       124
      5886         1       1.0
      4175         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       125
      5886         2       1.0
      4175         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       126
      5886         3       1.0
      4175         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       127
      5887         1       1.0
      4176         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       128
      5887         2       1.0
      4176         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       129
      5887         3       1.0
      4176         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       130
      5888         1       1.0
      4177         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       131
      5888         2       1.0
      4177         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       132
      5888         3       1.0
      4177         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       133
      5889         1       1.0
      4178         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       134
      5889         2       1.0
      4178         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       135
      5889         3       1.0
      4178         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       136
      8828         1       1.0
      7117         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       137
      8828         2       1.0
      7117         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       138
      8828         3       1.0
      7117         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       139
      8829         1       1.0
      7118         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       140
      8829         2       1.0
      7118         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       141
      8829         3       1.0
      7118         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       142
      8889         1       1.0
      7178         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       143
      8889         2       1.0
      7178         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       144
      8889         3       1.0
      7178         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       145
      8948         1       1.0
      7237         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       146
      8948         2       1.0
      7237         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       147
      8948         3       1.0
      7237         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       148
      8949         1       1.0
      7238         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       149
      8949         2       1.0
      7238         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       150
      8949         3       1.0
      7238         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       151
      9038         1       1.0
      7327         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       152
      9038         2       1.0
      7327         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       153
      9038         3       1.0
      7327         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       154
      9039         1       1.0
      7328         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       155
      9039         2       1.0
      7328         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       156
      9039         3       1.0
      7328         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       157
      9068         1       1.0
      7357         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       158
      9068         2       1.0
      7357         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       159
      9068         3       1.0
      7357         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       160
      9069         1       1.0
      7358         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       161
      9069         2       1.0
      7358         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       162
      9069         3       1.0
      7358         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       163
      9070         1       1.0
      7359         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       164
      9070         2       1.0
      7359         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       165
      9070         3       1.0
      7359         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       166
      9071         1       1.0
      7360         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       167
      9071         2       1.0
      7360         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       168
      9071         3       1.0
      7360         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       169
      9143         1       1.0
      7432         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       170
      9143         2       1.0
      7432         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       171
      9143         3       1.0
      7432         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       172
      9158         1       1.0
      7447         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       173
      9158         2       1.0
      7447         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       174
      9158         3       1.0
      7447         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       175
      9159         1       1.0
      7448         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       176
      9159         2       1.0
      7448         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       177
      9159         3       1.0
      7448         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       178
      9278         1       1.0
      7567         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       179
      9278         2       1.0
      7567         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       180
      9278         3       1.0
      7567         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       181
      9279         1       1.0
      7568         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       182
      9279         2       1.0
      7568         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       183
      9279         3       1.0
      7568         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       184
      9308         1       1.0
      7597         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       185
      9308         2       1.0
      7597         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       186
      9308         3       1.0
      7597         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       187
      9309         1       1.0
      7598         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       188
      9309         2       1.0
      7598         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       189
      9309         3       1.0
      7598         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       190
      9310         1       1.0
      7599         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       191
      9310         2       1.0
      7599         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       192
      9310         3       1.0
      7599         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       193
      9311         1       1.0
      7600         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       194
      9311         2       1.0
      7600         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       195
      9311         3       1.0
      7600         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       196
     12250         1       1.0
     10539         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       197
     12250         2       1.0
     10539         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       198
     12250         3       1.0
     10539         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       199
     12311         1       1.0
     10600         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       200
     12311         2       1.0
     10600         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       201
     12311         3       1.0
     10600         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       202
     12370         1       1.0
     10659         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       203
     12370         2       1.0
     10659         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       204
     12370         3       1.0
     10659         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       205
     12371         1       1.0
     10660         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       206
     12371         2       1.0
     10660         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       207
     12371         3       1.0
     10660         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       208
     12460         1       1.0
     10749         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       209
     12460         2       1.0
     10749         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       210
     12460         3       1.0
     10749         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       211
     12490         1       1.0
     10779         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       212
     12490         2       1.0
     10779         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       213
     12490         3       1.0
     10779         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       214
     12493         1       1.0
     10782         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       215
     12493         2       1.0
     10782         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       216
     12493         3       1.0
     10782         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       217
     12565         1       1.0
     10854         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       218
     12565         2       1.0
     10854         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       219
     12565         3       1.0
     10854         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       220
     12580         1       1.0
     10869         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       221
     12580         2       1.0
     10869         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       222
     12580         3       1.0
     10869         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       223
     12581         1       1.0
     10870         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       224
     12581         2       1.0
     10870         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       225
     12581         3       1.0
     10870         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       226
     12700         1       1.0
     10989         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       227
     12700         2       1.0
     10989         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       228
     12700         3       1.0
     10989         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       229
     12701         1       1.0
     10990         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       230
     12701         2       1.0
     10990         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       231
     12701         3       1.0
     10990         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       232
     12730         1       1.0
     11019         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       233
     12730         2       1.0
     11019         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       234
     12730         3       1.0
     11019         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       235
     12731         1       1.0
     11020         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       236
     12731         2       1.0
     11020         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       237
     12731         3       1.0
     11020         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       238
     12732         1       1.0
     11021         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       239
     12732         2       1.0
     11021         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       240
     12732         3       1.0
     11021         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       241
     12733         1       1.0
     11022         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       242
     12733         2       1.0
     11022         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       243
     12733         3       1.0
     11022         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         1
      1265         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         2
      1265         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         3
      1265         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         4
      1266         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         5
      1266         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         6
      1266         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         7
      1267         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         8
      1267         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         9
      1267         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        10
      1268         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        11
      1268         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        12
      1268         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        13
      1297         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        14
      1297         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        15
      1297         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        16
      1298         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        17
      1298         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        18
      1298         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        19
      1327         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        20
      1327         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        21
      1327         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        22
      1328         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        23
      1328         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        24
      1328         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        25
      1343         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        26
      1343         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        27
      1343         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        28
      1505         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        29
      1505         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        30
      1505         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        31
      1506         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        32
      1506         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        33
      1506         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        34
      1507         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        35
      1507         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        36
      1507         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        37
      1508         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        38
      1508         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        39
      1508         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        40
      1537         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        41
      1537         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        42
      1537         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        43
      1538         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        44
      1538         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        45
      1538         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        46
      1625         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        47
      1625         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        48
      1625         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        49
      1626         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        50
      1626         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        51
      1626         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        52
      1627         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        53
      1627         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        54
      1627         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        55
      1628         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        56
      1628         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        57
      1628         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        58
      1687         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        59
      1687         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        60
      1687         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        61
      1688         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        62
      1688         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        63
      1688         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        64
      1717         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        65
      1717         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        66
      1717         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        67
      1718         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        68
      1718         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        69
      1718         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        70
      1747         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        71
      1747         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        72
      1747         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        73
      1748         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        74
      1748         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        75
      1748         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        76
      1849         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        77
      1849         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        78
      1849         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        79
      1864         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        80
      1864         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        81
      1864         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        82
      1865         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        83
      1865         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        84
      1865         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        85
      1894         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        86
      1894         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        87
      1894         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        88
      1895         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        89
      1895         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        90
      1895         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        91
      1924         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        92
      1924         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        93
      1924         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        94
      1925         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        95
      1925         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        96
      1925         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        97
      1926         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        98
      1926         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        99
      1926         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       100
      1927         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       101
      1927         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       102
      1927         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       103
      3216         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       104
      3216         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       105
      3216         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       106
      3219         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       107
      3219         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       108
      3219         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       109
      3248         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       110
      3248         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       111
      3248         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       112
      3336         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       113
      3336         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       114
      3336         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       115
      3337         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       116
      3337         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       117
      3337         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       118
      3338         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       119
      3338         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       120
      3338         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       121
      3339         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       122
      3339         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       123
      3339         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       124
      3398         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       125
      3398         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       126
      3398         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       127
      3399         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       128
      3399         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       129
      3399         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       130
      3428         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       131
      3428         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       132
      3428         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       133
      3429         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       134
      3429         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       135
      3429         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       136
      6982         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       137
      6982         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       138
      6982         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       139
      6997         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       140
      6997         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       141
      6997         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       142
      6998         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       143
      6998         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       144
      6998         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       145
      7027         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       146
      7027         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       147
      7027         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       148
      7028         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       149
      7028         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       150
      7028         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       151
      7057         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       152
      7057         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       153
      7057         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       154
      7058         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       155
      7058         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       156
      7058         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       157
      7059         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       158
      7059         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       159
      7059         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       160
      7060         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       161
      7060         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       162
      7060         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       163
      8349         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       164
      8349         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       165
      8349         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       166
      8350         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       167
      8350         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       168
      8350         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       169
      8351         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       170
      8351         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       171
      8351         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       172
      8352         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       173
      8352         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       174
      8352         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       175
      8381         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       176
      8381         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       177
      8381         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       178
      8382         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       179
      8382         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       180
      8382         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       181
      8471         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       182
      8471         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       183
      8471         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       184
      8472         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       185
      8472         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       186
      8472         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       187
      8531         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       188
      8531         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       189
      8531         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       190
      8561         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       191
      8561         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       192
      8561         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       193
      8591         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       194
      8591         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       195
      8591         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       196
      8693         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       197
      8693         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       198
      8693         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       199
      8708         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       200
      8708         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       201
      8708         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       202
      8709         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       203
      8709         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       204
      8709         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       205
      8738         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       206
      8738         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       207
      8738         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       208
      8739         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       209
      8739         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       210
      8739         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       211
      8768         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       212
      8768         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       213
      8768         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       214
      8769         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       215
      8769         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       216
      8769         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       217
      8770         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       218
      8770         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       219
      8770         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       220
      8771         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       221
      8771         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       222
      8771         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       223
     10060         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       224
     10060         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       225
     10060         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       226
     10063         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       227
     10063         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       228
     10063         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       229
     10092         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       230
     10092         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       231
     10092         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       232
     10182         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       233
     10182         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       234
     10182         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       235
     10183         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       236
     10183         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       237
     10183         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       238
     10242         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       239
     10242         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       240
     10242         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       241
     10272         1       1.0
        38         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       242
     10272         2       1.0
        38         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
       243
     10272         3       1.0
        38         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         1
      1986         2       1.0
      8830         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         2
      1986         3       1.0
      8830         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         3
      1987         2       1.0
      8831         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         4
      1987         3       1.0
      8831         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         5
      2044         2       1.0
      8888         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         6
      2044         3       1.0
      8888         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         7
      2106         2       1.0
      8950         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         8
      2106         3       1.0
      8950         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         9
      2107         2       1.0
      8951         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        10
      2107         3       1.0
      8951         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        11
      5409         2       1.0
     12253         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        12
      5409         3       1.0
     12253         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        13
      5466         2       1.0
     12310         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        14
      5466         3       1.0
     12310         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        15
      5528         2       1.0
     12372         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        16
      5528         3       1.0
     12372         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        17
      5529         2       1.0
     12373         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        18
      5529         3       1.0
     12373         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         1
       337         2       1.0
      7239         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         2
       337         3       1.0
      7239         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         3
       338         2       1.0
      7177         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         4
       338         3       1.0
      7177         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         5
       353         2       1.0
      7240         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         6
       353         3       1.0
      7240         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         7
       487         2       1.0
      7120         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         8
       487         3       1.0
      7120         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         9
       488         2       1.0
      7119         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        10
       488         3       1.0
      7119         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        11
      3698         2       1.0
     10542         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        12
      3698         3       1.0
     10542         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        13
      3755         2       1.0
     10599         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        14
      3755         3       1.0
     10599         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        15
      3817         2       1.0
     10661         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        16
      3817         3       1.0
     10661         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        17
      3818         2       1.0
     10662         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        18
      3818         3       1.0
     10662         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         1
       292         2       1.0
      6892         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         2
       292         3       1.0
      6892         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         3
       293         2       1.0
      6907         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         4
       293         3       1.0
      6907         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         5
       308         2       1.0
      6908         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         6
       308         3       1.0
      6908         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         7
       545         2       1.0
      7871         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         8
       545         3       1.0
      7871         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         9
       546         2       1.0
      7870         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        10
       546         3       1.0
      7870         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        11
      1759         2       1.0
      8603         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        12
      1759         3       1.0
      8603         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        13
      1774         2       1.0
      8618         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        14
      1774         3       1.0
      8618         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        15
      1775         2       1.0
      8619         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        16
      1775         3       1.0
      8619         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        17
      2738         2       1.0
      9582         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        18
      2738         3       1.0
      9582         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         1
      3470         2       1.0
     10314         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         2
      3470         3       1.0
     10314         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         3
      3485         2       1.0
     10329         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         4
      3485         3       1.0
     10329         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         5
      3486         2       1.0
     10330         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         6
      3486         3       1.0
     10330         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         7
      4448         2       1.0
     11292         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         8
      4448         3       1.0
     11292         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         9
      4449         2       1.0
     11293         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        10
      4449         3       1.0
     11293         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        11
      5181         2       1.0
     12025         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        12
      5181         3       1.0
     12025         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        13
      5196         2       1.0
     12040         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        14
      5196         3       1.0
     12040         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        15
      5197         2       1.0
     12041         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        16
      5197         3       1.0
     12041         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        17
      6160         2       1.0
     13004         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        18
      6160         3       1.0
     13004         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         1
      1804         1       1.0
       787         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         2
      1804         2       1.0
       787         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         3
      1804         3       1.0
       787         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         4
      1819         1       1.0
      1118         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         5
      1819         2       1.0
      1118         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         6
      1819         3       1.0
      1118         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         7
      1820         1       1.0
       803         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         8
      1820         2       1.0
       803         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         9
      1820         3       1.0
       803         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        10
      2344         1       1.0
       848         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        11
      2344         2       1.0
       848         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        12
      2344         3       1.0
       848         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        13
      2404         1       1.0
       788         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        14
      2404         2       1.0
       788         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        15
      2404         3       1.0
       788         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        16
      8648         1       1.0
      6937         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        17
      8648         2       1.0
      6937         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        18
      8648         3       1.0
      6937         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        19
      8663         1       1.0
      6952         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        20
      8663         2       1.0
      6952         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        21
      8663         3       1.0
      6952         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        22
      8664         1       1.0
      6953         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        23
      8664         2       1.0
      6953         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        24
      8664         3       1.0
      6953         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        25
      9248         1       1.0
      7537         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        26
      9248         2       1.0
      7537         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        27
      9248         3       1.0
      7537         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         1
      5226         1       1.0
      3515         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         2
      5226         2       1.0
      3515         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         3
      5226         3       1.0
      3515         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         4
      5241         1       1.0
      3530         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         5
      5241         2       1.0
      3530         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         6
      5241         3       1.0
      3530         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         7
      5242         1       1.0
      3531         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         8
      5242         2       1.0
      3531         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         9
      5242         3       1.0
      3531         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        10
      5766         1       1.0
      4055         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        11
      5766         2       1.0
      4055         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        12
      5766         3       1.0
      4055         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        13
      5826         1       1.0
      4115         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        14
      5826         2       1.0
      4115         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        15
      5826         3       1.0
      4115         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        16
     12070         1       1.0
     10359         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        17
     12070         2       1.0
     10359         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        18
     12070         3       1.0
     10359         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        19
     12085         1       1.0
     10374         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        20
     12085         2       1.0
     10374         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        21
     12085         3       1.0
     10374         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        22
     12086         1       1.0
     10375         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        23
     12086         2       1.0
     10375         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        24
     12086         3       1.0
     10375         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        25
     12670         1       1.0
     10959         1      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        26
     12670         2       1.0
     10959         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
        27
     12670         3       1.0
     10959         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         1
      2075         2       1.0
      8919         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         2
      2075         3       1.0
      8919         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         1
       368         2       1.0
      7208         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         2
       368         3       1.0
      7208         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         1
      5497         2       1.0
     12341         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         2
      5497         3       1.0
     12341         3      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         1
      3786         2       1.0
     10630         2      -1.0
*CONSTRAINED_LINEAR_GLOBAL
         2
      3786         3       1.0
     10630         3      -1.0
